Marshal Integration v1 works!

diff --git a/boards/firechip/base-workloads/br-base/overlay/etc/init.d/S40network b/boards/firechip/base-workloads/br-base/overlay/etc/init.d/S40network
--- a/boards/firechip/base-workloads/br-base/overlay/etc/init.d/S40network
+++ b/boards/firechip/base-workloads/br-base/overlay/etc/init.d/S40network
@@ -2,37 +2,38 @@
 #
 # Start the network....
 #
-
 # Debian ifupdown needs the /run/network lock directory
 mkdir -p /run/network
 
+resolvconf_file="/etc/resolv.conf"
+rm -f $resolvconf_file
+echo "nameserver 172.16.0.3" > $resolvconf_file
+
+ifname=eth0
+read _ addr _ _ <<< $(/sbin/ip link | /bin/grep -A 1 "$ifname" | /usr/bin/tail -1)
+IFS=: read -r _ _ _ _ machigh maclow <<< $addr
+
 case "$1" in
-  start)
-	printf "Starting network: "
-	/sbin/ifup -a
-	ifname=eth0
-	if test -r "/sys/class/net/${ifname}/address" ; then
-		/sbin/ip link set dev "$ifname" up &&
-		IFS=: read -r _ _ _ _ machigh maclow < "/sys/class/net/${ifname}/address" &&
-		/sbin/ip addr add "172.16.$((16#$machigh)).$((16#$maclow))/16" dev "$ifname"
-	fi
-#	/sbin/ifup eth0
-	[ $? = 0 ] && echo "OK" || echo "FAIL"
-	;;
-  stop)
-	printf "Stopping network: "
-	/sbin/ifdown -a
-#	/sbin/ifdown eth0
-	[ $? = 0 ] && echo "OK" || echo "FAIL"
-	;;
-  restart|reload)
-	"$0" stop
-	"$0" start
-	;;
-  *)
-	echo "Usage: $0 {start|stop|restart}"
-	exit 1
+	start)
+		printf "Starting network: "
+        /bin/sed -i -e "1,/^address/{s/^address.*/address 172.16.$((16#$machigh)).$((16#$maclow))/;}" /etc/network/interfaces
+        sbin/ifup -a
+        [ $? = 0 ] && echo "OK" || echo "FAIL"
+        ;;
+    stop)
+        printf "Stopping network: "
+        /sbin/ifdown -a
+        /bin/sed -i -e "1,/^address/{s/^address.*/address firemarshal_ip_addr_uninitialized/;}" /etc/network/interfaces
+        [ $? = 0 ] && echo "OK" || echo "FAIL"
+        ;;
+    restart|reload)
+        "$0" stop
+        "$0" start
+        ;;
+    *)
+        echo "Usage: $0 {start|stop|restart}"
+        exit 1
+
 esac
 
 exit $?
-
